#!/bin/bash

# Copyright (c) 2021 Sebastian Steenssøe
# All rights reserved.

# This source code is licensed under the MIT-style license found in the
# LICENSE file in the root directory of this source tree.

# Author: Sebastian Steenssøe
# Date Created: 02/09/2021
# Last Modified: 02/09/2021

# Description
# Helper functions

# Usage
# get_help
# get_repos [organization name]
# get_open_issues [organization name]
# get_closed_issues [organization name]

get_help() {
    printf "Organisation specific extension for gh cli to retrieve different statistics

\033[1mUSAGE\033[0m
    gh orgstats [flags]

\033[1mFLAGS\033[0m
    --org       Name of organization
    --stats     Comma separated string of statistics
                stats available: repos, closed_issues, open_issues
    --plain     Get numbers without pretty output
    --json      Output as json

\033[1mEXAMPLES\033[0m
    $ gh orgstats --org cli --stats open_issues,closed_issues,repos
    $ gh orgstats --org cli --stats open_issues --plain

\033[1mLEARN MORE\033[0m
    https://github.com/VildMedPap/gh-orgstats
"
}

get_repos() {
    QUERY='
    query ($login: String!) {
        organization(login: $login) {
            repositories(isFork: false) {
                totalCount
            }
        }
    }
    '

    gh api graphql -F login="${1}" -f query="${QUERY}" --jq '.data.organization.repositories.totalCount'
}

get_open_issues() {
    QUERY='
    query ($endCursor: String, $login: String!) {
        organization(login: $login) {
            repositories(isFork: false, first: 100, after: $endCursor) {
                pageInfo {
                    endCursor
                    hasNextPage
                }
                edges {
                    node {
                        issues(states: OPEN) {
                            totalCount
                        }
                    }
                }
            }
        }
    }
    '

    open_issues_arr=$(gh api graphql --paginate -F login="${1}" -f query="${QUERY}" --jq '.data.organization.repositories.edges.[].node.issues.totalCount')
    echo ${open_issues_arr[@]} | sed 's/ /+/g' | bc
}

get_closed_issues() {
    QUERY='
    query ($endCursor: String, $login: String!) {
        organization(login: $login) {
            repositories(isFork: false, first: 100, after: $endCursor) {
                pageInfo {
                    endCursor
                    hasNextPage
                }
                edges {
                    node {
                        issues(states: CLOSED) {
                            totalCount
                        }
                    }
                }
            }
        }
    }
    '

    closed_issues_arr=$(gh api graphql --paginate -F login="${1}" -f query="${QUERY}" --jq '.data.organization.repositories.edges.[].node.issues.totalCount')
    echo ${closed_issues_arr[@]} | sed 's/ /+/g' | bc
}

get_members() {
    QUERY='
    query ($endCursor: String, $login: String!) {
        organization(login: $login) {
            membersWithRole(first: 100, after: $endCursor) {
                pageInfo {
                    endCursor
                    hasNextPage
                }
                edges {
                    node {
                        login
                    }
                }
            }
        }
    }
    '

    members_arr=$(gh api graphql --paginate -F login="${1}" -f query="${QUERY}" --jq '[.data.organization.membersWithRole.edges.[].node.login]|length')
    echo ${members_arr[@]} | sed 's/ /+/g' | bc
}